// <auto-generated />
using System;
using Kontrolnaja_Rabota_Po_ASP_API.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kontrolnaja_Rabota_Po_ASP_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kontrolnaja_Rabota_Po_ASP_API.Db.OrderDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfFormation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Shiphr")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Shiphr")
                        .IsUnique();

                    b.ToTable("_orderDbs");
                });

            modelBuilder.Entity("Kontrolnaja_Rabota_Po_ASP_API.Db.ProductDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("_productsDb");
                });

            modelBuilder.Entity("Kontrolnaja_Rabota_Po_ASP_API.Db.ProductInOrderDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderDbId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductDbId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityProductInOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderDbId");

                    b.HasIndex("ProductDbId");

                    b.ToTable("_productInOrderDb");
                });

            modelBuilder.Entity("Kontrolnaja_Rabota_Po_ASP_API.Db.ProductInOrderDb", b =>
                {
                    b.HasOne("Kontrolnaja_Rabota_Po_ASP_API.Db.OrderDb", "OrderDb")
                        .WithMany("ProducsInOrder")
                        .HasForeignKey("OrderDbId");

                    b.HasOne("Kontrolnaja_Rabota_Po_ASP_API.Db.ProductDb", "ProductDb")
                        .WithMany("ProducsInOrder")
                        .HasForeignKey("ProductDbId");

                    b.Navigation("OrderDb");

                    b.Navigation("ProductDb");
                });

            modelBuilder.Entity("Kontrolnaja_Rabota_Po_ASP_API.Db.OrderDb", b =>
                {
                    b.Navigation("ProducsInOrder");
                });

            modelBuilder.Entity("Kontrolnaja_Rabota_Po_ASP_API.Db.ProductDb", b =>
                {
                    b.Navigation("ProducsInOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
